name: Test CI

on: [push]

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Enable node
        uses: actions/setup-node@master
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Lint types and code
        run: npm run lint

  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Enable node
        uses: actions/setup-node@master
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Run jest
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_ICU_DATA: node_modules/full-icu
        run: npm run test:cov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
